### ISSUE TITLE
Incorrect focus handling by LiveCode

### ISSUE THREAD

**Issue by quasiyoke** [lttb/reshadow-website#3]
Steps to reproduce:

1. In the first "Basics" example make "simple button" text staying on the same row with the component tag using Delete key,
1. put the cursor after `<button>` tag,

   ![](https://i109.fastpic.ru/big/2019/0322/aa/3c74cb12b37c74971f119fc7f58cf5aa.png)
1. press Delete once again,
1. cursor jumps on the third "file".

**Comment by lttb** [comment]
Thank you for the issue! I'll try to fix that soon
