### ISSUE TITLE
LiveCode sometimes breaks on the Firefox

### ISSUE THREAD

**Issue by quasiyoke** [lttb/reshadow-website#4]
Firefox 65.0.1 (64-bit)

After several refreshes may work correctly.

![](https://i109.fastpic.ru/big/2019/0322/e5/2badd2357bc70a673e38fe92388c79e5.png)

**Comment by lttb** [comment]
Hi! Thank you for the issue.

It looks like a problem with unstable styles loading from `https://unpkg.com/codemirror@5.42.0/lib/codemirror.css` in `docz`

https://github.com/pedronauck/docz/blob/63b72b6a7c57d97e599d50d4e4addc3b41c1fb01/packages/docz-theme-default/src/styles/global.ts#L6

I think it should be bundled

**Comment by quasiyoke** [comment]
Can't reproduce anymore. It seems like fixed.
